### PR TITLE
Upgrade to polkadot v0.9.26

### PR DESCRIPTION
**Pull request by CertainLach**
Superseeds https://github.com/UniqueNetwork/unique-chain/pull/431

### CODE REVIEW

**Comment by CertainLach** [comment]
Includes https://github.com/UniqueNetwork/unique-chain/pull/441, but for upgraded substrate

**Comment by CertainLach** [comment]
Тут требуется обернуть вызов в `with_transactional`, т.к атрибут `#[transactional]` мы убрали с вызовов в polkadot v0.9.25 
https://github.com/UniqueNetwork/unique-chain/blob/566036f697e11f621a64fdeb0dc019d1b6628a9a/pallets/scheduler/src/lib.rs#L441

В оригинальном substrate так не делают, т.к там используют `call.dispatch`, а у нас всё идёт через `extrinsic.apply`, а потому 
https://github.com/UniqueNetwork/unique-chain/blob/566036f697e11f621a64fdeb0dc019d1b6628a9a/runtime/opal/src/lib.rs#L1003

**Comment by CertainLach** [comment]
Hey, seems like you need to have changelog and version bumps for your PR?

Don't worry, i've got you covered, if you have proper commit messages, then changelog generated by me should be okay for you

# Changes

After your confirmation, I will append the following entries to changelogs of packages:

## unique-runtime-common v0.9.25 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-unique-scheduler v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-structure v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-rmrk-core v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Remove `#[transactional]` from extrinsics 460acb32b6b2de837bf8d3e556365902ec89e427

Every extrinsic now runs in transaction implicitly, and
`#[transactional]` on pallet dispatchable is now meaningless

Upstream-Change: https://github.com/paritytech/substrate/issues/10806

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-unique v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Remove `#[transactional]` from extrinsics 460acb32b6b2de837bf8d3e556365902ec89e427

Every extrinsic now runs in transaction implicitly, and
`#[transactional]` on pallet dispatchable is now meaningless

Upstream-Change: https://github.com/paritytech/substrate/issues/10806

- refactor: Switch to new prefix removal methods 5d9665e065c72fc755ac18272d4a3d7b6ce990c4

New methods allows to call `remove_prefix` with limit multiple times
in the same block
However, we don't use prefix removal limits, so upgrade is
straightforward

Upstream-Change: https://github.com/paritytech/substrate/pull/11490

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## up-data-structs v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-rmrk-equip v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Remove `#[transactional]` from extrinsics 460acb32b6b2de837bf8d3e556365902ec89e427

Every extrinsic now runs in transaction implicitly, and
`#[transactional]` on pallet dispatchable is now meaningless

Upstream-Change: https://github.com/paritytech/substrate/issues/10806

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-refungible v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Switch to new prefix removal methods 5d9665e065c72fc755ac18272d4a3d7b6ce990c4

New methods allows to call `remove_prefix` with limit multiple times
in the same block
However, we don't use prefix removal limits, so upgrade is
straightforward

Upstream-Change: https://github.com/paritytech/substrate/pull/11490

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## evm-coder v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## up-rpc v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## opal-runtime v0.9.25 (Patch bump)

### Bugfixes

- Add missing config keys 430decbe3b0db3ee2a81207ef3bb1406dce18b10

New parity changes expect that System pallet has id 0, as it is declared
in most parachains

Because pallet id was changed, tx_version was increased, because old
transactions will not work with new version of chain

- Add missing config keys 93792bc194cc479312ae954005ef8af79c0e0edd

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-evm-contract-helpers v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## tests v0.1.1 (Patch bump)

### Bugfixes

- Add missing config keys 430decbe3b0db3ee2a81207ef3bb1406dce18b10

New parity changes expect that System pallet has id 0, as it is declared
in most parachains

Because pallet id was changed, tx_version was increased, because old
transactions will not work with new version of chain

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## uc-rpc v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-evm-coder-substrate v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## unique-node v0.9.25 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Use export-genesis state from cumulus 03cdd4abdb57cac24a54aa6024076801ae6f0900

We had our implementation for some reason, however it is now broken, and
I see no reason to keep it, as upstream implements exact same options

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-evm-migration v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Remove `#[transactional]` from extrinsics 460acb32b6b2de837bf8d3e556365902ec89e427

Every extrinsic now runs in transaction implicitly, and
`#[transactional]` on pallet dispatchable is now meaningless

Upstream-Change: https://github.com/paritytech/substrate/issues/10806

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## rmrk-rpc v0.0.2 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-fungible v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Switch to new prefix removal methods 5d9665e065c72fc755ac18272d4a3d7b6ce990c4

New methods allows to call `remove_prefix` with limit multiple times
in the same block
However, we don't use prefix removal limits, so upgrade is
straightforward

Upstream-Change: https://github.com/paritytech/substrate/pull/11490

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-nonfungible v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Switch to new prefix removal methods 5d9665e065c72fc755ac18272d4a3d7b6ce990c4

New methods allows to call `remove_prefix` with limit multiple times
in the same block
However, we don't use prefix removal limits, so upgrade is
straightforward

Upstream-Change: https://github.com/paritytech/substrate/pull/11490

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-common v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- refactor: Switch to new prefix removal methods 5d9665e065c72fc755ac18272d4a3d7b6ce990c4

New methods allows to call `remove_prefix` with limit multiple times
in the same block
However, we don't use prefix removal limits, so upgrade is
straightforward

Upstream-Change: https://github.com/paritytech/substrate/pull/11490

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-evm-transaction-payment v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## pallet-inflation v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b
## unique-rpc v0.1.1 (Patch bump)

### Other changes

- build: Upgrade polkadot to v0.9.26 50a343ea000907169d4ea26178d2d52985df27bf

- build: Upgrade polkadot to v0.9.25 04c093485e1aacc051e5e682f45c022470ae177b


# Bumps

I may not be able to describe reason for bump, but they should be required:

unique-runtime-common `0.9.24` -> `0.9.25`

- changelog generator decided to bump to Patch

pallet-unique-scheduler `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-structure `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-rmrk-core `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-unique `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

up-data-structs `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-rmrk-equip `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-refungible `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

evm-coder `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

up-rpc `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

opal-runtime `0.9.24` -> `0.9.25`

- changelog generator decided to bump to Patch

pallet-evm-contract-helpers `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

tests `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

uc-rpc `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-evm-coder-substrate `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

unique-node `0.9.24` -> `0.9.25`

- changelog generator decided to bump to Patch

pallet-evm-migration `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

rmrk-rpc `0.0.1` -> `0.0.2`

- changelog generator decided to bump to Patch

pallet-fungible `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-nonfungible `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-common `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-evm-transaction-payment `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

pallet-inflation `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

unique-rpc `0.1.0` -> `0.1.1`

- changelog generator decided to bump to Patch

**Comment by CertainLach** [comment]
Прогнал генератор чейнжлогов (см. сообщение и последний коммит), перед мержом его потребуется снова прогнать, т.к версии там будут уже другие

**Review by kozyrevdev — CHANGES_REQUESTED** [review]
@CertainLach нужно дообновиться https://github.com/paritytech/polkadot/tree/release-v0.9.26-1

**Pull request closed without merging**
